### ISSUE TITLE
AttributeError: function 'bleu_zero_init' not found (on Windows 10)

### ISSUE THREAD

**Issue by j0st** [thompsonb/prism#7]
I am trying to generate paraphrases but after executing
```
python generate_paraphrases.py test_bin --batch-size 8 \
   --prefix-size 1 \
   --path $MODEL_DIR/checkpoint.pt \
   --prism_a 0.006 --prism_b 4  
```
I get this error: 
Traceback (most recent call last):
  File "paraphrase_generation\generate_paraphrases.py", line 478, in <module>
    cli_main()
  File "paraphrase_generation\generate_paraphrases.py", line 474, in cli_main
    main(args)
  File "paraphrase_generation\generate_paraphrases.py", line 359, in main
    scorer = bleu.Scorer(tgt_dict.pad(), tgt_dict.eos(), tgt_dict.unk())
  File "C:\Users\jost_\Anaconda3\envs\prismenv\lib\site-packages\fairseq\bleu.py", line 67, in __init__
    self.reset()
  File "C:\Users\jost_\Anaconda3\envs\prismenv\lib\site-packages\fairseq\bleu.py", line 73, in reset
    C.bleu_zero_init(ctypes.byref(self.stat))
  File "C:\Users\jost_\Anaconda3\envs\prismenv\lib\ctypes\__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\jost_\Anaconda3\envs\prismenv\lib\ctypes\__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'bleu_zero_init' not found

(I am using Windows 10)

**Comment by mjpost** [comment]
I'm not sure we can support Windows 10. But what version of sacrebleu do you have? You might try downgrading to 1.4.8.

**Comment by j0st** [comment]
Thanks for the answer but downgrading to 1.4.8 didn't work (I used the newest version before)
